server:
  port: 8808

spring:

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          #        show_sql: true
          format_sql: true
          use_sql_comments: true
          default_batch_fetch_size: 1000
      open-in-view: false

    mvc:
      path-match:
        matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
